(deftheme valkea
  "Created 2020-02-02.")

(custom-theme-set-variables
 'valkea
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(package-selected-packages (quote (color-theme-sanityinc-solarized zzz-to-char popup-kill-ring company flycheck htmlize ox-twbs zerodark-theme which-key use-package swiper spaceline rainbow-mode rainbow-delimiters projectile pretty-mode mark-multiple linum-relative hungry-delete expand-region dashboard avy async)))
 '(custom-safe-themes (quote ("4cf3221feff536e2b3385209e9b9dc4c2e0818a69a1cdb4b522756bcdf4e00a4" "4aee8551b53a43a883cb0b7f3255d6859d766b6c5e14bcb01bed572fcbef4328" "1068ae7acf99967cc322831589497fee6fb430490147ca12ca7dd3e38d9b552a" default)))
 '(ansi-color-names-vector ["#282c34" "#ff6c6b" "#98be65" "#da8548" "#61afef" "#c678dd" "#1f5582" "#abb2bf"]))

(custom-theme-set-faces
 'valkea
 '(cursor ((((class color) (min-colors 89)) (:background "#abb2bf"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#24282f" :foreground "#687080"))))
 '(border ((((class color) (min-colors 89)) (:foreground "#3a3f4b"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#3a3f4b"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#3e4451" :foreground "#abb2bf" :underline nil))))
 '(region ((((class color) (min-colors 89)) (:background "#3e4451"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#3e4451" :foreground "#abb2bf"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#ddbd78" :foreground "#3e4451"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#666666" :foreground "#ddbd78"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#2c323b" :underline unspecified :inherit nil))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(match ((((class color) (min-colors 89)) (:background "#3d4a41"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#687080" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#9eac8c"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold :background "#4c3840"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#38394c" :height 0.9 :foreground "#61afef" :box (:line-width 6 :color "#38394c")))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#22252c" :height 0.9 :foreground "#abb2bf" :box (:line-width 6 :color "#22252c")))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line-inactive))))
 '(error ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(success ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:height 0.9 :foreground "#61afef" :background "#22252c"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:height 0.9 :foreground "#61afef" :background "#3a3f4b"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:background unspecified (:inherit mode-line)))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#687080" :background "#282c34"))))
 '(line-number ((((class color) (min-colors 89)) (:foreground "#687080" :background "#22252c"))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:foreground "#61afef" :background "#22252c"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background unspecified :foreground "#3e4451" :inverse-video unspecified))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background unspecified :foreground "#3e4451" :inverse-video unspecified))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background unspecified :foreground "#3e4451" :inverse-video unspecified))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background unspecified :foreground "#3e4451" :inverse-video unspecified))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background "#ff6c6b" :foreground "#282c34" :weight bold :inverse-video nil))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background unspecified :foreground "#ff6c6b" :inverse-video unspecified))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:inherit whitespace-space))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:inherit whitespace-space))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background unspecified :foreground "#3e4451" :inverse-video unspecified))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background "#da8548" :foreground "#3e4451" :inverse-video unspecified))))
 '(link ((((class color) (min-colors 89)) (:foreground "#61afef" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#61afef" :underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#3e4451" :box (:line-width 1 :color "#687080")))))
 '(widget-button ((((class color) (min-colors 89)) (:inherit link))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#3a3f4b" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#3e4451" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:background "#3e4451" :box (:line-width 2 :style pressed-button)))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold :height 1.4))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(compilation-warning ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold :inverse-video nil))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#61afef" :background "#38394c" :weight bold))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#22252c" :foreground "#abb2bf"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#22252c" :foreground "#c678dd"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:background "#61afef" :foreground "#abb2bf"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#22252c" :foreground "#abb2bf"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#22252c"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#38394c"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold :background "#22252c"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold :background "#38394c"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#c678dd" :background "#3a3f4b" :weight bold))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:foreground "#abb2bf" :background "#3a3f4b"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:foreground "#abb2bf" :background "#3a3f4b"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#282c34"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :background "#4c3840" :weight bold))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#61afef" :background "#38394c" :weight bold))))
 '(org-date ((((class color) (min-colors 89)) (:background "#3a3f4b"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#ff6c6b"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#abb2bf"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#da8548"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "PeachPuff3" :weight bold))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "#9eac8c" :weight bold))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(outline-6 ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(outline-7 ((((class color) (min-colors 89)) (:foreground "PeachPuff3" :weight bold))))
 '(outline-8 ((((class color) (min-colors 89)) (:foreground "#9eac8c" :weight bold))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#38394c" :foreground "#61afef" :weight bold))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold :background "#38394c" :box 1))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#abb2bf" :weight bold))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#22252c"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "#3d4a41" :foreground "#9eac8c" :height 0.9))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "#3d4a41" :foreground "#9eac8c" :height 0.9))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:background "#48384c" :weight bold :foreground "#c678dd"))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:foreground "#da8548"))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(ivy-match-required-face ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :background "#4c3840" :weight bold))))
 '(ivy-modified-buffer ((((class color) (min-colors 89)) (:foreground "#ff6c6b"))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(ivy-highlight-face ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) :foreground "#ff6c6b" :weight bold :background "#4c3840")))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) :foreground "#ff6c6b" :weight bold :background "#4c3840")))
 '(epa-validity-high ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(epa-validity-low ((((class color) (min-colors 89)) (:foreground "#abb2bf"))))
 '(epa-validity-disabled ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold :background "#4c3840"))))
 '(epa-field-name ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(epa-field-body ((((class color) (min-colors 89)) (:foreground "#da8548"))))
 '(default ((((class color) (min-colors 89)) (:background "#282c34" :foreground "#abb2bf")))))

(provide-theme 'valkea)
